### ISSUE TITLE
EarningsPerMonthMatrixTab.createMonthColumn: assertion failed: Unknown column layout data

### ISSUE THREAD

**Issue by cmaoling** [cmaoling/portfolio#81]
ri Feb 21 07:12:15 GMT 2020
Internal Error

org.eclipse.core.runtime.AssertionFailedException: assertion failed: Unknown column layout data
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.jface.layout.AbstractColumnLayout.layoutTableTree(AbstractColumnLayout.java:194)
	at org.eclipse.jface.layout.AbstractColumnLayout.layout(AbstractColumnLayout.java:262)
	at org.eclipse.jface.layout.TableColumnLayout.updateColumnData(TableColumnLayout.java:110)
	at org.eclipse.jface.layout.AbstractColumnLayout.lambda$0(AbstractColumnLayout.java:76)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1379)
	at org.eclipse.swt.widgets.TableColumn.gtk_size_allocate(TableColumn.java:415)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2001)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6014)
	at org.eclipse.swt.internal.gtk.OS._Call(Native Method)
	at org.eclipse.swt.internal.gtk.OS.Call(OS.java:882)
	at org.eclipse.swt.widgets.Widget.fixedSizeAllocateProc(Widget.java:1007)
	at org.eclipse.swt.widgets.Display.fixedSizeAllocateProc(Display.java:1517)
	at org.eclipse.swt.internal.gtk.GTK._gtk_widget_size_allocate(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_widget_size_allocate(GTK.java:9391)
	at org.eclipse.swt.widgets.Control.forceResize(Control.java:884)
	at org.eclipse.swt.widgets.Table.createItem(Table.java:773)
	at org.eclipse.swt.widgets.TableColumn.createWidget(TableColumn.java:199)
	at org.eclipse.swt.widgets.TableColumn.<init>(TableColumn.java:83)
	at org.eclipse.jface.viewers.TableViewerColumn.createColumn(TableViewerColumn.java:83)
	at org.eclipse.jface.viewers.TableViewerColumn.<init>(TableViewerColumn.java:61)
	at org.eclipse.jface.viewers.TableViewerColumn.<init>(TableViewerColumn.java:43)
	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.createMonthColumn(EarningsPerMonthMatrixTab.java:214)
	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.createColumns(EarningsPerMonthMatrixTab.java:145)
	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.updateColumns(EarningsPerMonthMatrixTab.java:300)
	at name.abuchen.portfolio.ui.views.earnings.EarningsPerMonthMatrixTab.lambda$2(EarningsPerMonthMatrixTab.java:129)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at name.abuchen.portfolio.ui.views.earnings.EarningsViewModel.fireUpdateChange(EarningsViewModel.java:369)
	at name.abuchen.portfolio.ui.views.earnings.EarningsViewModel.recalculate(EarningsViewModel.java:227)
	at name.abuchen.portfolio.ui.views.earnings.EarningsView.notifyModelUpdated(EarningsView.java:91)
	at name.abuchen.portfolio.ui.editor.PortfolioPart.onRecalculationNeeded(PortfolioPart.java:372)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at name.abuchen.portfolio.ui.editor.ClientInput.setDirty(ClientInput.java:125)
	at name.abuchen.portfolio.ui.editor.ClientInput.lambda$10(ClientInput.java:487)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4586)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by cmaoling** [comment]
No clue opened https://github.com/buchen/portfolio/issues/1743
