### ISSUE TITLE
IngDiba import failes due to PeerCache NULL POINTER EXCEPTION

### ISSUE THREAD

**Issue by cmaoling** [cmaoling/portfolio#99]
*Wed Jul 20 06:42:58 GMT 2022
Während "Kontoumsätze der Ing-DIBA" ist ein interner Fehler aufgetreten.

java.lang.UnsupportedOperationException: java.lang.NullPointerException
	at name.abuchen.portfolio.ui.wizards.datatransfer.ReviewExtractedItemsPage$14.run(ReviewExtractedItemsPage.java:750)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException
	at name.abuchen.portfolio.datatransfer.PeerCache.lookupPeerByName(PeerCache.java:107)
	at name.abuchen.portfolio.datatransfer.PeerCache.lookup(PeerCache.java:76)
	at name.abuchen.portfolio.datatransfer.csv.BaseCSVExtractor.getPeer(BaseCSVExtractor.java:149)
	at name.abuchen.portfolio.datatransfer.csv.CSVAccountTransactionExtractor.extract(CSVAccountTransactionExtractor.java:110)
	at name.abuchen.portfolio.datatransfer.csv.BaseCSVExtractor.extract(BaseCSVExtractor.java:87)
	at name.abuchen.portfolio.datatransfer.csv.CSVAccountTransactionExtractor.extract(CSVAccountTransactionExtractor.java:1)
	at name.abuchen.portfolio.datatransfer.csv.CSVImporter.createItems(CSVImporter.java:965)
	at name.abuchen.portfolio.ui.wizards.datatransfer.CSVImportWizard$ExtractorProxy.extract(CSVImportWizard.java:53)
	at name.abuchen.portfolio.ui.wizards.datatransfer.ReviewExtractedItemsPage$14.run(ReviewExtractedItemsPage.java:737)
	... 1 more

**Comment by cmaoling** [comment]
ISBN im Ersten Feld scheint das Problem zu sein.

**Comment by cmaoling** [comment]
Solved with 761040b075fb708994ed0b0cc39a6f6bb5b0ca8a
